services:
  #######################################################
  # jaeger
  #######################################################
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  #######################################################
  # zipkin
  #######################################################
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  #######################################################
  # prometheus
  #######################################################
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  #######################################################
  # grafana
  #######################################################
  grafana:
    container_name: grafana
    pull_policy: if_not_present
    restart: on-failure
    image: grafana/grafana
    ports:
      - 3000:3000

  #######################################################
  # opentelemetry
  #######################################################
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  microservice-a:
    container_name: microservice-a
    build:
      context: .
    environment:
      - TITLE=Microservice A
      - CONTENT=Este é um microserviço de demonstração pra PDI 2024 1° semestre
      - BACKGROUND_COLOR=green
      - RESPONSE_TIME=1000
      - EXTERNAL_CALL_URL=http://microservice-b:8181
      - EXTERNAL_CALL_METHOD=GET
      - REQUEST_NAME_OTEL=microservice-a-request
      - OTEL_SERVICE_NAME=microservice-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8080
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector

  microservice-b:
    container_name: microservice-b
    build:
      context: .
    environment:
      - TITLE=Microservice B
      - CONTENT=[Microservice B] Resposta de chamada externa - Este é um microserviço de demonstração pra PDI 2024 1° semestre
      - BACKGROUND_COLOR=blue
      - EXTERNAL_CALL_URL=http://microservice-c:8282
      - EXTERNAL_CALL_METHOD=GET
      - RESPONSE_TIME=2000
      - REQUEST_NAME_OTEL=microservice-b-request
      - OTEL_SERVICE_NAME=microservice-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8181
    ports:
      - "8181:8181"
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector

  microservice-c:
    container_name: microservice-c
    build:
      context: .
    environment:
      - TITLE=Microservice C
      - CONTENT=[Microservice C] Resposta de chamada externa - Este é um microserviço de demonstração pra PDI 2024 1° semestre
      - BACKGROUND_COLOR=red
      - RESPONSE_TIME=2000
      - REQUEST_NAME_OTEL=microservice-c-request
      - OTEL_SERVICE_NAME=microservice-c
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8282
    ports:
      - "8282:8282"
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector
